---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: knative-serving
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./knative/serving
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: knative-serving
  patches:
    - patch: |-
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: config-network
          namespace: knative-serving
        data:
          ingress-class: kourier.ingress.networking.knative.dev      
      target:
        name: config-network
        kind: ConfigMap
        namespace: knative-serving