---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: knative-serving
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./knative/serving
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: knative-serving

